# render.yaml - V3 with the corrected dockerCommand property

services:
  # A. The Web Service (Dashboard UI)
  - type: web
    name: smart-order-intake-web
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
    disks:
      - name: shared-output
        mountPath: /app/output

  # B. The Background Worker (Order Processor)
  - type: worker
    name: smart-order-intake-worker
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    
    # --- THIS IS THE FIX ---
    # Use 'dockerCommand' to override the Dockerfile's CMD for this specific service.
    dockerCommand: "python worker.py"
    # --- END OF FIX ---
    
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    disks:
      - name: shared-output
        mountPath: /app/output

# This section defines the shared disk itself
disks:
  - name: shared-output
    sizeGB: 1