# render.yaml - V5, correcting the YAML structure for disk mounts

services:
  # A. The Web Service (Dashboard UI)
  - type: web
    name: smart-order-intake-web
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
    
    # --- FIX #1: This section should NOT be a list. ---
    # The 'disk' key takes a direct object, so we remove the hyphen.
    disk:
      name: shared-output
      mountPath: /app/output

  # B. The Background Worker (Order Processor)
  - type: worker
    name: smart-order-intake-worker
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    dockerCommand: "python worker.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
        
    # --- FIX #2: Remove the hyphen here as well. ---
    disk:
      name: shared-output
      mountPath: /app/output

# --- FIX #3: The top-level key to DEFINE disks must be plural. ---
disks:
  - name: shared-output
    sizeGB: 1