# render.yaml - V7, Final Correction. No hyphen under the 'disk:' key.

services:
  # A. The Web Service (Dashboard UI)
  - type: web
    name: smart-order-intake-web
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    healthCheckPath: /health
    
    # --- THIS IS THE FINAL FIX ---
    # The key is 'disk:' (singular) and the value is a direct object (no hyphen).
    disk:
      name: shared-output
      mountPath: /app/output
      sizeGB: 1 # The size must be defined on first use.
      
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1

   # B. The Order Processor (as a free Cron Job)
  - type: cron
    name: smart-order-intake-cron
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # Use your repo URL
    branch: main
    schedule: "*/15 * * * *" # This means "run every 15 minutes"
    dockerCommand: "python worker.py"
    disk:
      name: shared-output
      mountPath: /app/output
    envVars:
      - key: GEMINI_API_KEY
        sync: false