# render.yaml - V6, based on the latest Render spec for inline disk definitions.

services:
  # A. The Web Service (Dashboard UI)
  - type: web
    name: smart-order-intake-web
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    healthCheckPath: /health
    # --- THIS IS THE FINAL, CORRECT STRUCTURE ---
    # The disk is defined directly within the service that uses it.
    disks:
      - name: shared-output
        mountPath: /app/output
        sizeGB: 1 # Define the size here
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1

  # B. The Background Worker (Order Processor)
  - type: worker
    name: smart-order-intake-worker
    runtime: docker
    repo: https://github.com/AkaashThawani/Hackathon # This should be your repo URL
    branch: main
    dockerCommand: "python worker.py"
    # The worker also attaches to the same disk by referencing its name.
    disks:
      - name: shared-output
        mountPath: /app/output
        # The size only needs to be defined once. Render is smart enough
        # to know it's the same disk.
    envVars:
      - key: GEMINI_API_KEY
        sync: false